name: expense_manager

services:
  postgres:
    image: postgres:17
    container_name: expense_manager_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build: .
    container_name: expense_manager_django
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
